config/routes.rb
AtlasMapsGeo::Application.routes.draw do
  resources :geo_objects

  root :to => "geo_objects#index"

  Blacklight.add_routes(self)
  HydraHead.add_routes(self)

  devise_for :users

end

app/models/geo_object.rb
class GeoObject < ActiveFedora::Base
  has_metadata :name=>'rightsMetadata', :type=> Hydra::Datastream::RightsMetadata
  has_metadata :name => 'descMetadata', :type => ActiveFedora::SimpleDatastream do |m|
    m.field "description", :string
    m.field "path_to_cop",:string
    m.field "path_to_image", :string
    m.field "publish_year", :integer
    m.field "title", :string
    m.field "geo_lat", :string
    m.field "geo_lng", :string
  end


  def to_solr (solr_doc = {})
    super
    solr_doc['title_t'] = self.title
    solr_doc['location_p']= "#{self.geo_lat},#{self.geo_lng}"

    return solr_doc
  end


  delegate_to 'descMetadata', [:description, :geo_lat, :geo_lng, :path_to_cop, :path_to_image, :publish_year, :title], :unique => true
end

app/controllers/geo_objects_controller.rb
class GeoObjectsController < ApplicationController
  # GET /geo_objects
  # GET /geo_objects.json
  def index
    @geo_objects = GeoObject.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @geo_objects }
    end
  end

  # GET /geo_objects/1
  # GET /geo_objects/1.json
  def show
    @geo_object = GeoObject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @geo_object }
    end
  end

  # GET /geo_objects/new
  # GET /geo_objects/new.json
  def new
    @geo_object = GeoObject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @geo_object }
    end
  end

  # GET /geo_objects/1/edit
  def edit
    @geo_object = GeoObject.find(params[:id])
  end

  # POST /geo_objects
  # POST /geo_objects.json
  def create
    @geo_object = GeoObject.new(params[:geo_object])

    respond_to do |format|
      if @geo_object.save
        format.html { redirect_to @geo_object, notice: 'Geo object was successfully created.' }
        format.json { render json: @geo_object, status: :created, location: @geo_object }
      else
        format.html { render action: "new" }
        format.json { render json: @geo_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /geo_objects/1
  # PUT /geo_objects/1.json
  def update
    @geo_object = GeoObject.find(params[:id])

    respond_to do |format|
      if @geo_object.update_attributes(params[:geo_object])
        format.html { redirect_to @geo_object, notice: 'Geo object was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @geo_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geo_objects/1
  # DELETE /geo_objects/1.json
  def destroy
    @geo_object = GeoObject.find(params[:id])
    @geo_object.destroy

    respond_to do |format|
      format.html { redirect_to geo_objects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/geo_objects_helper.rb
module GeoObjectsHelper
end

app/views/geo_objects/_form.html.erb
<%= form_for @geo_object, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :publish_year, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :publish_year, :class => 'year_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :geo_lat, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :geo_lat, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :geo_lng, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :geo_lng, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :path_to_image, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :path_to_image, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :path_to_cop, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :path_to_cop, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                geo_objects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/geo_objects/edit.html.erb
<%- model_class = GeoObject -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/geo_objects/index.html.erb
<%- model_class = GeoObject -%>
<script src="http://www.openlayers.org/api/OpenLayers.js"></script>


<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:publish_year) %></th>
      <th><%= model_class.human_attribute_name(:geo_lat) %></th>
      <th><%= model_class.human_attribute_name(:geo_lng) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:path_to_image) %></th>
      <th><%= model_class.human_attribute_name(:path_to_cop) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @geo_objects.each do |geo_object| %>
      <tr>
        <td><%= link_to geo_object.id, geo_object_path(geo_object) %></td>
        <td><%= geo_object.title %></td>
        <td><%= geo_object.publish_year %></td>
        <td><%= geo_object.geo_lat %></td>
        <td><%= geo_object.geo_lng %></td>
        <td><%= geo_object.description %></td>
        <td><%= image_tag geo_object.path_to_image %></td>
        <td><%= link_to geo_object.path_to_cop %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_geo_object_path(geo_object), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      geo_object_path(geo_object),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_geo_object_path,
            :class => 'btn btn-primary' %>
<hr>
<div class="hero-unit">
<iframe width="80%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
        src="http://www.openstreetmap.org/export/embed.html?bbox=12.0,55.00,10.00,45.04819&layer=mapnik" style="border: 1px solid black"></iframe>
<br /> <small>
  <a href="http://www.openstreetmap.org/?lat=38.99434&lon=-77.03244&zoom=14&layers=M">View Larger Map</a>
</small>
</div>


</body>

app/views/geo_objects/new.html.erb
<%- model_class = GeoObject -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/geo_objects/show.html.erb
<%- model_class = GeoObject -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @geo_object.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:publish_year) %>:</strong></dt>
  <dd><%= @geo_object.publish_year %></dd>
  <dt><strong><%= model_class.human_attribute_name(:geo_lat) %>:</strong></dt>
  <dd><%= @geo_object.geo_lat %></dd>
  <dt><strong><%= model_class.human_attribute_name(:geo_lng) %>:</strong></dt>
  <dd><%= @geo_object.geo_lng %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><blockquote><%= @geo_object.description %></blockquote></dd>
  <dt><strong><%= model_class.human_attribute_name(:path_to_image) %>:</strong></dt>
  <dd><%= image_tag @geo_object.path_to_image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:path_to_cop) %>:</strong></dt>
  <dd><%= link_to '' + @geo_object.title + ' i cop', @geo_object.path_to_cop %></dd>
</dl>



<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              geo_objects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_geo_object_path(@geo_object), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              geo_object_path(@geo_object),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>


<div>
  <iframe class="span5" width="600px" height="300px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://www.openstreetmap.org/export/embed.html?bbox=-22.9,33.3,54.2,70.6&amp;
  layer=transportmap&amp;marker=<%= @geo_object.geo_lat %>,<%= @geo_object.geo_lng %>" style="border: 1px solid black"></iframe><br /><small><a href="http://www.openstreetmap.org/?lat=51.949999999999996&amp;lon=15.650000000000002&amp;zoom=3&amp;layers=T&amp;mlat=54.16243&amp;mlon=9.75586">View Larger Map</a></small>
</div>
</small>